class CarSpec < ApplicationRecord
  belongs_to :car

  belongs_to :engine_oil_viscosity, optional: true, class_name: "Parts::EngineOilViscosity"
  belongs_to :engine_oil_quantity, optional: true, class_name: "Parts::EngineOilQuantity"
  belongs_to :engine_oil_filter, optional: true, class_name: "Parts::EngineOilFilter"
  belongs_to :brake_fluid_type, optional: true, class_name: "Parts::BrakeFluidType"
  belongs_to :brake_pad, optional: true, class_name: "Parts::BrakePad"
  belongs_to :brake_rotor, optional: true, class_name: "Parts::BrakeRotor"
  belongs_to :tire_size, optional: true, class_name: "Parts::TireSize"
  belongs_to :tire_brand, optional: true, class_name: "Parts::TireBrand"
  belongs_to :transmission_fluid_type, optional: true, class_name: "Parts::TransmissionFluidType"
  belongs_to :transmission_fluid_quantity, optional: true, class_name: "Parts::TransmissionFluidQuantity"
  belongs_to :coolant_type, optional: true, class_name: "Parts::CoolantType"
  belongs_to :engine_air_filter, optional: true, class_name: "Parts::EngineAirFilter"
  belongs_to :cabin_air_filter, optional: true, class_name: "Parts::CabinAirFilter"
  belongs_to :wiper_blade_size, optional: true, class_name: "Parts::WiperBladeSize"
  belongs_to :headlight, optional: true, class_name: "Parts::Headlight"
  belongs_to :taillight, optional: true, class_name: "Parts::Taillight"
  belongs_to :turn_signal_light, optional: true, class_name: "Parts::TurnSignalLight"
  belongs_to :license_plate_light, optional: true, class_name: "Parts::LicensePlateLight"
  belongs_to :battery, optional: true, class_name: "Parts::Battery"
  belongs_to :serpentine_belt, optional: true, class_name: "Parts::SerpentineBelt"
  belongs_to :thermostat, optional: true, class_name: "Parts::Thermostat"
end
